spring.datasource.url=jdbc:postgresql://postgres:5432/b2u_hub
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=8081

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

app.mail.enabled=true
app.mail.mode=console
app.mail.from=sassichahine68@gmail.com

app.ai.gemini.enabled=false
app.ai.gemini.model=gemini-2.5-flash

spring.config.import=optional:classpath:application-local.properties

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:data-docker.sql
