spring.application.name=PI
spring.datasource.url=jdbc:postgresql://localhost:5433/b2u_hub
spring.datasource.username=postgres
spring.datasource.password=1312

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081

spring.config.import=optional:classpath:application-local.properties

app.mail.enabled=true
app.mail.mode=console
app.mail.from=sassichahine68@gmail.com

jwt.secret=b2u-hub-super-secret-key-must-be-at-least-32-chars-2024
jwt.expiration=86400000

cloudinary.cloud_name=die3g00yu
cloudinary.api_key=484237194643237
cloudinary.api_secret=VnE1naZJFFUj-Inx2CtwIOZhQdI
huggingface.api-key=dummy-key
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/google