apiVersion: v1
kind: ConfigMap
metadata:
  name: b2u-backend-config
  namespace: b2u-hub
data:
  SPRING_PROFILES_ACTIVE: docker
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/b2u_hub
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: "0000"
